power<-read.csv("household_power_consumption.txt", header=TRUE, sep=";", na.strings = "?")
power2<-subset(power,Date=="1/2/2007" | Date=="2/2/2007")
power2$datetime<-paste(power2$Date,power2$Time)
power2$datetime2 <- strptime(power2$datetime, format="%d/%m/%Y %H:%M:%S")
par(mfrow=c(1,1))
plot(power2$datetime2,power2$Sub_metering_1, type="n", ylab="Energy sub metering", xlab="")
lines(power2$datetime2,power2$Sub_metering_1)
lines(power2$datetime2,power2$Sub_metering_2, col="red")
lines(power2$datetime2,power2$Sub_metering_3, col="blue")
legend("topright", legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black","red","blue"),lty=c(1,1,1),cex=.6)